// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCSg2HdLEHRzUORp2xXjVDV9HBLb02eF8',
    appId: '1:349000765489:web:5f442185df2dce659c0510',
    messagingSenderId: '349000765489',
    projectId: 'chaty-app-699e9',
    authDomain: 'chaty-app-699e9.firebaseapp.com',
    storageBucket: 'chaty-app-699e9.appspot.com',
    measurementId: 'G-G22YD83FYQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDb3H4tdfuc2Eg8VBZl1tW9_5Yhfkhd5Cc',
    appId: '1:349000765489:android:a2e20bc2e3546c089c0510',
    messagingSenderId: '349000765489',
    projectId: 'chaty-app-699e9',
    storageBucket: 'chaty-app-699e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFgXB8j0uOVIMiJIMoaC7k5vGMKh6GLjA',
    appId: '1:349000765489:ios:5b5f2cb9c58039cf9c0510',
    messagingSenderId: '349000765489',
    projectId: 'chaty-app-699e9',
    storageBucket: 'chaty-app-699e9.appspot.com',
    iosBundleId: 'com.example.chaty',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFgXB8j0uOVIMiJIMoaC7k5vGMKh6GLjA',
    appId: '1:349000765489:ios:5b5f2cb9c58039cf9c0510',
    messagingSenderId: '349000765489',
    projectId: 'chaty-app-699e9',
    storageBucket: 'chaty-app-699e9.appspot.com',
    iosBundleId: 'com.example.chaty',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDCSg2HdLEHRzUORp2xXjVDV9HBLb02eF8',
    appId: '1:349000765489:web:b25b204c1d70dd889c0510',
    messagingSenderId: '349000765489',
    projectId: 'chaty-app-699e9',
    authDomain: 'chaty-app-699e9.firebaseapp.com',
    storageBucket: 'chaty-app-699e9.appspot.com',
    measurementId: 'G-XSG2JWHL4V',
  );

}